### ISSUE TITLE
How to compile this ESP project ?

### ISSUE THREAD

**Issue by Noschvie** [revk/SolarSystem#178]
Hello
is there a "HowTo" compiling this project ?
Using ESP-IDF 4.3 under Windows gets an Error "Failed to resolve component 'ESP32-RevK'."
thanks
Norbert

![grafik](https://user-images.githubusercontent.com/48217146/137532913-b7987224-714e-418e-ab34-e88dacdd12e8.png)

**Comment by revk** [comment]
No idea on windows, did you recursively fetch everything?

**Comment by Noschvie** [comment]
It seems that perl is needed, isn't it?

```
...
-- Found PythonInterp: C:/Users/nosch/.espressif/python_env/idf4.3_py3.8_env/Scr
ipts/python.exe (found version "3.8.7")
-- Could NOT find Perl (missing: PERL_EXECUTABLE)
-- App "SS" version: V1.0448
...
```

**Comment by Noschvie** [comment]
Now I changed my development platform to Linux / Debian 11.1 running as VM under Hyper-V and get the project to be compiled and built.

My question : what have to be changed to define / config my local wifi ( SSID and password) ?

thanks, Norbert

**Comment by revk** [comment]
make menuconfig
Allows all the defaults to be set including SSID, etc.

**Comment by Noschvie** [comment]
> 
> 
> make menuconfig
Allows all the defaults to be set including SSID, etc.

... recompiled and connected to the local wifi. Perfect! Thanks
