### ISSUE TITLE
Authenticated bug

### ISSUE THREAD

**Issue by Serenity-Whitefall** [revk/SolarSystem#183]
I spotted some bugs whilst coding the API enhancement...

https://github.com/revk/SolarSystem/blob/b17ef467bc8be78533f6f216191b6a4629d5daec/www/provisiondevice.cgi#L59

It seems this always says "Device is authenticated." regardless of whether the database value is true or false. Should it actually be "if authenticated=true" ?

Also I'm not sure it can even be set to true in the database.

https://github.com/revk/SolarSystem/blob/b17ef467bc8be78533f6f216191b6a4629d5daec/solarsystem.c#L1302-L1318

For it to be set to true, secureid would have to evaluate to true in line 1316, however if it did evaluate to true, then it would have entered the if section at 1302 and therefore never reach the else section at 1310.

**Comment by revk** [comment]
It looks wrong on both counts, indeed.

**Comment by revk** [comment]
Ok I am not sure what I was intending for that field. Clearly the display can easily be fixed with the =true. But the setting does look wrong, and probably should be commented out for now. Ultimately if never set we should remove the field.

**Comment by revk** [comment]
Commented out
