### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by Serenity-Whitefall** [revk/SolarSystem#184]
https://github.com/revk/SolarSystem/blob/b17ef467bc8be78533f6f216191b6a4629d5daec/solarsystem.c#L992-L1003

I think this sql_free_result at line 1000 doesn't want to be inside the else.

Also I'm not sure of the purpose of line 994 "deviceid = v". It gets overwritten in line 998 and if there wasn't a result returned then it would return from the function at line 1002 anyway?

**Comment by revk** [comment]
I agree on the free, that looks like a leek. Setting deviceid may be used later anyway as it has wider scope even after the return.

**Comment by ghenry** [comment]
Since thus us an open source project you should put in. Coverity auto scan. Very helpful. See here https://github.com/SentryPeer/SentryPeer/actions/runs/1704107864/workflow

**Comment by revk** [comment]
No idea how you do that...

**Comment by ghenry** [comment]
Sign up:

https://scan.coverity.com/users/sign_up

Add your project.

Get your key from the bottom of that page.

Add it to https://github.com/revk/SolarSystem/settings/secrets/actions like
attached.

then create this file in a .github/worksflow folder in your repo:

https://github.com/SentryPeer/SentryPeer/blob/main/.github/workflows/coverity-scan.yml

Change these lines:

https://github.com/SentryPeer/SentryPeer/blob/main/.github/workflows/coverity-scan.yml#L57
https://github.com/SentryPeer/SentryPeer/blob/main/.github/workflows/coverity-scan.yml#L36
https://github.com/SentryPeer/SentryPeer/blob/main/.github/workflows/coverity-scan.yml#L64

etc.

That's it.

Want me to do a fork and PR for you? You do the sign up bit and get your
Project Token from the Settings page in Coverity.

Thanks.

**Comment by revk** [comment]
Yeh, a PR would be easiest for me as I have never done that! Give me a mo.

**Comment by revk** [comment]
Ok not finding the settings, sorry, not trying to be thick here!

**Comment by ghenry** [comment]
Settings on GitHub or Coverity?

**Comment by revk** [comment]
Coverity - I have account settings. It has a thing asking me to add projects...

**Comment by revk** [comment]
Ok I added solar system on there

**Comment by revk** [comment]
Ah, Ok I have a token.

**Comment by ghenry** [comment]
Cool. Are you going to figure it out using the example SentryPeer one?

**Comment by revk** [comment]
Somewhat out of my depth with this one, to be honest. I don't even see a .github directory let alone workflow, so I assume I have to make them. Happy to take any help I can get!

**Comment by ghenry** [comment]
Yeah, create that folder and file in your local git repo and then commit
etc.

It will then show up here:

https://github.com/revk/SolarSystem/actions

You'll need to read the yml file and update it on how to build your project
as if you're on a Ubuntu machine. Ubuntu containers come with these
installed:

https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-Readme.md

Also, other things you can do for reporting issues:

https://github.com/SentryPeer/SentryPeer/tree/main/.github/ISSUE_TEMPLATE

and the free analysis tools from Github:

https://github.com/SentryPeer/SentryPeer/tree/main/.github/workflows

https://github.com/SentryPeer/SentryPeer/blob/main/.github/workflows/codeql-analysis.yml

**Comment by revk** [comment]
OK on debian... I may try and catch up with this later...

**Comment by ghenry** [comment]
Feel free to give me repo access and add me to the coverity project
and I'll set it all up for you. Then revoke my project access.
Probably easiest :)
