### ISSUE TITLE
no log when unlocking a door from the web interface

### ISSUE THREAD

**Issue by relaystar** [revk/SolarSystem#225]
if you manually unlock a door from the web interface, no log is recorded.  I think this should count as an event.

**Comment by revk** [comment]
Oh, I thing there should be, I'll take a look.

**Comment by revk** [comment]
Ah, it logs if you then open based on a remote unlock.
```
{"ts":"2023-04-03T10:11:43Z","node":"DoorOffice","trigger":"remote"}
```
That said, it would be nice to log the unlock itself.

**Comment by revk** [comment]
Ok logs now.
