### ISSUE TITLE
Try WolfSSL instead of mbedTLS

### ISSUE THREAD

**Issue by revk** [revk/SolarSystem#67]
mbedTLS has huge memory leak for various types of non clean close.

Causes all sorts of issues.

**Comment by ghenry** [comment]
What's the reason for using mbedTLS vs say WolfSSL or OpenSSL? Size?

**Comment by revk** [comment]
Just what came with ESP IDF to be honest.

Is WolfSSL better?

**Comment by ghenry** [comment]
Ah, OK. I'm really enjoying WolfSSL. Great examples - https://github.com/wolfSSL/wolfssl/tree/master/examples and lovely docs - https://github.com/wolfSSL/wolfssl-examples/blob/master/tls/README.md

**Comment by revk** [comment]
After much looking, seems all I need is :-

`git submodule add --recursive https://github.com/espressif/esp-wolfssl.git components/esp-wolfssl`

This provides the options in `make menuconfig`, yay!

Sadly, that does not actually work. It seems not to actually build the library!

`make: *** No rule to make target '/projects/github/SolarSystem/ESP32/components/esp-wolfssl/wolfssl/lib/esp32/libwolfssl.a', needed by '/projects/github/SolarSystem/ESP32/build/SS.elf'.  Stop.`

And help welcome.

**Comment by ghenry** [comment]
No sure. See what they say
https://github.com/espressif/esp-wolfssl/issues/10

**Comment by ghenry** [comment]
I'm just following the docs myself to see if I can get it build. The ESPs are nice. Soooo many options in menuconfig. Just like buidling the Linux kernel.

**Comment by revk** [comment]
Apparently handling (legacy) `make` command was not in there and will be soon.

**Comment by revk** [comment]
Needs an extra component.mk to fix for Make for now.

But works.
